### ISSUE TITLE
Encoding issue ? 

### ISSUE THREAD

**Issue by krptg** [h3llrais3r/Auto-Subliminal#13]
Hi,

Just tried your software. I like having a webui for subliminal, this is exactly what I was looking for. I however got an issue that prevents Auto-Subliminal to scan my media disks as follow in the logs : 

`'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)`

Is this an encoding issue ?

Using latest master, will try with develop.

**Comment by h3llrais3r** [comment]
Please enable debug logging and post it here.

**Comment by lgromb** [comment]
There it is : https://pastebin.com/sG5CNDKv

I have to change my filenames then ? Can I see which file is responsible ?

**Comment by h3llrais3r** [comment]
You can only see it when DEBUG is enabled.
Please go to logfile settings, choose debug and save it.
It will normally auto restart the application with debug enabled and execute the disk scanning.

**Comment by stefxg** [comment]
Hello, your prog is great thanks :)

But I have same problem
I have enable debug log, I will post them tomorrow

**Comment by stefxg** [comment]
web side log
https://pastebin.com/SbMmGx3U

server side log
https://pastebin.com/ibgb0wgp

**Comment by h3llrais3r** [comment]
I can't reproduce it since I'm running it on Windows.
Can you stop the application, delete te log file and restart it?
I want to know the default encoding of your OS.
I want to see something like this at the beginning of your log file:
```
2017-09-20 19:44:42,180 INFO     [MainThread :: __main__] Running application with PID: 1716
2017-09-20 19:44:42,181 INFO     [MainThread :: __main__] System encoding: cp1252
2017-09-20 19:44:42,183 INFO     [MainThread :: __main__] Config version: 8
2017-09-20 19:44:42,184 INFO     [MainThread :: __main__] Db version: 7
```
Can you also send me the system info? You can find it at the System menu - Info link. Screenshot of the general system info is ok.

**Comment by h3llrais3r** [comment]
anyone who can give me feedback on this?

**Comment by h3llrais3r** [comment]
A lot of changes have been implemented related to encoding in the `development` branch.
Feel free to reopen or create a new issue when the problem still occurs in the development branch.
If yes, provide a proper debug log.
