### ISSUE TITLE
Add support to pt-BR

### ISSUE THREAD

**Issue by 9zdot** [h3llrais3r/Auto-Subliminal#138]
Subliminal has pt-BR as a supported language using the following command:
subliminal  download -l pt-BR -p thesubdb -p opensubtitles <file>

Portuguese from portugal is totally different language.
Is it possible to add support to Brazilian Portuguese as a default language?

**Comment by h3llrais3r** [comment]
If you use `pt-BR`, what does it use as language suffix for your srt file?
Will this be `filename.pt-BR.srt`?

**Comment by h3llrais3r** [comment]
I've just implemented the support in the `development` branch with commit 00eda76fc405534fbdedf2c3e17afa81b7076b9b.
Can you try it out and give me feedback?

**Comment by 9zdot** [comment]
Hi, sorry to take to much time to give you a feedback.
The change that you did is working partially.
Below is my configuration:
![C855915F-618F-4C93-95CE-B7D795274E80](https://user-images.githubusercontent.com/5232795/54575076-8af7d100-49d1-11e9-9fbd-2afb830c5f85.jpeg)

Only pt-BR is selected but the system is searching both, pt and pt-BR as you can see in the below image:
![103D5D22-262C-4514-8474-04C19EE09B19](https://user-images.githubusercontent.com/5232795/54574843-a6aea780-49d0-11e9-84f6-2b6a62371e3c.jpeg)
Last downloaded section is only showing pt subtitles 
![4DA7FCEA-9F74-454E-8EBF-7F291A572AE1](https://user-images.githubusercontent.com/5232795/54574930-01e09a00-49d1-11e9-9c3c-01e9169821f4.jpeg)
But what is really happening is that auto-subliminal is downloading both languages and keeping the movie in the wanted section.

**Comment by h3llrais3r** [comment]
You'll have to flush your wanted items and run the diskscan again after changes the language. :wink: 
Normally you should only have the pt-BR after that (with Brazilian flag).

**Comment by 9zdot** [comment]
@h3llrais3r you’re right. Flush the cache solved the first issue. My bad :)
I isolated the auto-subliminal in a docker container, installing everything from scratch.
I deleted all the subtitles, started the container and put the diskscan to run again. This time only Brazilian flag appeared in the wanted section but the issue with the downloaded subtitles remains.
The only flag shown in the downloaded section is Portugal’s flag.
This is only a cosmetic issue as the subtitles that were downloaded are in pt-BR

**Comment by h3llrais3r** [comment]
@9zdot 
I did some more changes in the development branch, which should fix the remaining issue. :wink: 
Can you retry again? Please make sure to hard reload your page because I also made javascript changes.

**Comment by 9zdot** [comment]
@h3llrais3r everything is working fine now.
Thanks a lot!

**Comment by h3llrais3r** [comment]
Good to hear. :wink: 
Will close the issue once development is merged in master.

**Comment by h3llrais3r** [comment]
Released to master.
