### ISSUE TITLE
Any plans of creating a release in pypi for this package instead of using setup.py install?

### ISSUE THREAD

**Issue by msdos** [h3llrais3r/Auto-Subliminal#14]
So it can be installed like subliminal, just using `pip` and avoid having python dependencies in the `lib` folder itself.

**Comment by msdos** [comment]
I don't know if it's possible to keep both ways, will have to think about it.

**Comment by h3llrais3r** [comment]
Current version doesn't need an install anymore. All libraries are packed inside the lib folder of the application.
