### ISSUE TITLE
Implement ability to force encoding

### ISSUE THREAD

**Issue by Zeusy123** [h3llrais3r/Auto-Subliminal#16]
Hi ther,e just testing your script out and looks awesome, so thankyou!!

I do think you should enable ability to force the encoding type as sublinimal now allows,

-e UTF8 

for example ^^

**Comment by morpheus65535** [comment]
Replace this line: https://github.com/h3llrais3r/Auto-Subliminal/blob/1029d2df387fe53ced234fc2a543c2150c8384aa/autosubliminal/subdownloader.py#L59

With:
subliminal.save_subtitles(video, self._download_item['subtitles'][video], self._download_item['single'], encoding='utf-8')

**Comment by h3llrais3r** [comment]
I suppose you only want this for UTF-8? Or do you want to give any possible encoding?

**Comment by morpheus65535** [comment]
I think that UTF-8 should work well. In bazarr, I only encode in UTF-8.

**Comment by Zeusy123** [comment]
personally just utf* for me, but as your catering for all, i would guess all encoding types:)
btw, GREAT work!!!

**Comment by h3llrais3r** [comment]
I think I will start with an option to force utf-8. I can always change it later when there is need for it.

**Comment by h3llrais3r** [comment]
I've provided the option in the develop branch. Can you try it out and give feedback?

**Comment by morpheus65535** [comment]
Question: is there a benefit of NOT storing them as utf8? I would put it as an option but as normal behavior. But it’s your choice! :-)

**Comment by h3llrais3r** [comment]
I rather keep the original encoding as default. That's also how subliminal works by default ;)

**Comment by morpheus65535** [comment]
Yes I understand. Of course, it’s up to you and you made Auto-Subliminal a very configurable software.

**Comment by Zeusy123** [comment]
shall test the encoding for you, in a bit, just waiting on library updating.

**Comment by h3llrais3r** [comment]
> Yes I understand. Of course, it’s up to you and you made Auto-Subliminal a very configurable software.
Thanks, I already spend lot of time on it. 😉 
But even when it's not the default option, you can at least now enable it.
So please give it a try with latest develop branch.

**Comment by Zeusy123** [comment]
Heres alternative for you to help:)

def get_subtitle_encoding(filename):

    known_encodings = ["utf_8","cp1252","utf_16_le","utf_16_be","asci","iso8859_1","iso8859_2","iso8859_3","iso8859_4","iso8859_5","iso8859_6","iso8859_7","iso8859_8","iso8859_9","iso8859_10","iso8859_11","iso8859_13","iso8859_14","iso8859_15","iso8859_16","big5","big5hkscs","cp037","cp424","cp437","cp500","cp720","cp737","cp775","cp850","cp852","cp855","cp856","cp857","cp858","cp860","cp861","cp862","cp863","cp864","cp865","cp866","cp869","cp874","cp875","cp932","cp949","cp950","cp1006","cp1026","cp1140","cp1250","cp1251","cp1253","cp1254","cp1255","cp1256","cp1257","cp1258","euc_jp","euc_jis_2004","euc_jisx0213","euc_kr","gb2312","gbk","gb18030","hz","iso2022_jp","iso2022_jp_1","iso2022_jp_2","iso2022_jp_2004","iso2022_jp_3","iso2022_jp_ext","iso2022_kr","johab","koi8_r","koi8_u","mac_cyrillic","mac_greek","mac_iceland","mac_latin2","mac_roman","mac_turkish","ptcp154","shift_jis","shift_jis_2004","shift_jisx0213","utf_32","utf_32_be","utf_32_le","utf_16","utf_7","utf_8_sig"]
    srt_encodings = ["UTF-8","cp1252","UTF-16LE","UTF-16BE","","ISO-8859-1","ISO-8859-2","ISO-8859-3","ISO-8859-4","ISO-8859-5","ISO-8859-6","ISO-8859-7","ISO-8859-8","ISO-8859-9","ISO-8859-10","ISO-8859-11","ISO-8859-13","ISO-8859-14","ISO-8859-15","ISO-8859-16","big5","big5hkscs","cp037","cp424","cp437","cp500","cp720","cp737","cp775","cp850","cp852","cp855","cp856","cp857","cp858","cp860","cp861","cp862","cp863","cp864","cp865","cp866","cp869","cp874","cp875","cp932","cp949","cp950","cp1006","cp1026","cp1140","cp1250","cp1251","cp1253","cp1254","cp1255","cp1256","cp1257","cp1258","euc_jp","euc_jis_2004","euc_jisx0213","euc_kr","gb2312","gbk","gb18030","hz","iso2022_jp","iso2022_jp_1","iso2022_jp_2","iso2022_jp_2004","iso2022_jp_3","iso2022_jp_ext","iso2022_kr","johab","koi8_r","koi8_u","mac_cyrillic","mac_greek","mac_iceland","mac_latin2","mac_roman","mac_turkish","ptcp154","shift_jis","shift_jis_2004","shift_jisx0213","utf_32","utf_32_be","utf_32_le","utf_16","utf_7","utf_8_sig"]

**Comment by morpheus65535** [comment]
@Zeusy123 have a good use case to test, I'll leave it to him.

**Comment by h3llrais3r** [comment]
@Zeusy123 Thanks for the tip, but I'm only going to support utf-8 for now.
Adding a dropdown is a possibility, but I doubt there is a lot of request for alternative encodings.
