### ISSUE TITLE
Download forced subtitles from OpenSubtitles

### ISSUE THREAD

**Issue by ramonleon627** [h3llrais3r/Auto-Subliminal#165]
Please consider adding an option to get forced subtitles from OpenSubtitles.  They have added functionality in their API that identifies forced subtitles.

https://forum.opensubtitles.org/viewtopic.php?f=8&t=15856

**Comment by h3llrais3r** [comment]
Since I'm using subliminal as library for downloading the subtitles (not a custom implementation), please introduce the feature request in https://github.com/Diaoul/subliminal/issues
