### ISSUE TITLE
AutoSubliminal not identifying embedded subtitles?

### ISSUE THREAD

**Issue by Zeusy123** [h3llrais3r/Auto-Subliminal#17]
I have source with all laungages attached to the source using 2codes en for enlgish etc...

looking at logs:

2017-12-06 19:53:19,592 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 19:53:21,793 ERROR Imdb id not found for Fish Called Wanda, A (1988)
2017-12-06 19:53:21,871 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 19:53:24,023 ERROR Imdb id not found for Fistful of Dollars, A (1964)
2017-12-06 19:53:24,131 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 19:53:26,907 ERROR Imdb id not found for Five (2016)
2017-12-06 19:53:27,157 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 19:53:32,937 ERROR Imdb id not found for Fleetwood Mac, The Dance (1997)
2017-12-06 19:53:34,388 ERROR Imdb id not found for Flight (2012)
2017-12-06 19:53:37,227 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 19:53:37,930 ERROR Imdb id not found for The Flintstones & WWE, Stone Age Smackdown (2
2017-12-06 19:53:38,025 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 19:53:39,654 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 19:53:41,342 ERROR Embedded subtitle track name u'Web (en)' is not a valid language

en = english, so why doesnt it identify it?

**Comment by h3llrais3r** [comment]
Please provide debug log.

**Comment by Zeusy123** [comment]
AGH:( This could be a killer for me:(
All my srts are attached  using mkvmerge named Web (en) (to identify source - and language)

Any idea how I can make your script idenfiy it? or if its babefish how to edit that?

**Comment by h3llrais3r** [comment]
I have an idea, but don't you have a problem with your media player? Because afaik the players must read the language and I doubt that 'web (en)' will be identified as a valid 'en' language...

**Comment by Zeusy123** [comment]
h3hhraiser3r, are you on discord?
Dont want to explain in open chat if you understand?
morpheus65535 is a coder of Bazarr a script similar to yours using sublinimal etc... I recoemmd both you guys combine your skillz:)

As for me I'm a tester, new ideas kinda guy:)

So i think we could all help one another and speedup dev on AutoSub!

https://discord.gg/MH2e2eb

Deelte the link above after reading please:)

**Comment by h3llrais3r** [comment]
No not on discord.
Why wouldn't I explain? I just said I had an idea, but that's by implementing some custom code to identity 'web (en)' as 'en'. But like I said before, 'web (en)' is not a valid language, and I want to know if media players support this...

**Comment by Zeusy123** [comment]
Sorry I mean I dont want to explain in public chant, but no matters:)
I'll look at way to get all my attached srts renamed to just en or ar etc..

**Comment by h3llrais3r** [comment]
I suppose you can do that with mkv tools (in bulk?)

**Comment by morpheus65535** [comment]
We've been trying to make this with mkvpropedit which is part of mkvtoolnix but we can't get the right syntax. In fact, we're not sure it's possible at all:
https://github.com/mbunkus/mkvtoolnix/issues/2169

@h3llrais3r Are you aware of a python library that could do this?

**Comment by h3llrais3r** [comment]
Sorry, don't know such a library, but you should be able to do something with mkvtoolnix...
But I don't think you can select it based on the track name, you need to select based on track number... 
See https://mkvtoolnix.download/doc/mkvpropedit.html#mkvpropedit.edit_selectors
`track:tn` -> `t` is identifier, `n` is number

But I suppose this is not that easy for everything because it will probably be different for different shows/movies...

Next to that, I checked some non touched mkv's of myself, and language should be in ISO3 code. (eng instead of en).
![image](https://user-images.githubusercontent.com/1945295/33783991-5987b17a-dc5f-11e7-8355-1b5af6c6d7d4.png)

**Comment by Zeusy123** [comment]
Thanks h3llrais3r for your help;) Seriously appreciated.

Yes cant select by name and all track numbers will be different.
Guess only option is to either leave it as is, or find a way to remove all srts from mkv files.  Then edit my srt attaching to mkv script so it just names it en.  I perfer 2 digit country codes as the NAME its more commonly used but yes for language its 3 digit.

So whats best way to delete ALL subtitlex attached to a file and do same to all mkv files found in recursive folders?:)

Then ill reatach all correctly again, will take few weeks but better to make it perfect.

**Comment by h3llrais3r** [comment]
Language should be 3 digit code... That's how mkvtoolnix shows it also... 

![image](https://user-images.githubusercontent.com/1945295/33784876-d5f44e46-dc62-11e7-90fe-18e548940920.png)

**Comment by h3llrais3r** [comment]
Since this is not an issue, I'll close this.

**Comment by Zeusy123** [comment]
yes language = 3 digit correct, but my "Web (en)" is in the name,
I need to edit the name of the srt (not language code).

Hope that make it clearer?:)

**Comment by h3llrais3r** [comment]
But what do you have as language? Because like I said before, the tool is parsing the language, not the name... So the name doesn't matter at all...

**Comment by Zeusy123** [comment]
3 digit language codes :)
eng etc..

**Comment by h3llrais3r** [comment]
Then there should be no problem...

**Comment by Zeusy123** [comment]
strange one :) ok close this ill keep eye on things again thanks for help:)

**Comment by h3llrais3r** [comment]
Please check some of the files that give errors with mkvtoolnix and see what's set as language.

**Comment by Zeusy123** [comment]
heres an example:

2017-12-06 20:47:57,884 ERROR    Embedded subtitle track name u'Eight Diagram Pole Fighter (1984)-alE13' is not a valid language
2017-12-06 20:47:57,900 ERROR    Embedded subtitle track name u'Eight Diagram Pole Fighter (1984)-alE13' is not a valid language
2017-12-06 20:47:58,697 ERROR    Imdb id not found for Eight Diagram Pole Fighter (1984)

![eight](https://user-images.githubusercontent.com/24862324/33785820-b14b4378-dc5e-11e7-8e82-153fb6fa9d22.png)

**Comment by Zeusy123** [comment]
pls delete the images after you view it m8ty:)

**Comment by h3llrais3r** [comment]
Strange... Can you enable debug logging in the tool, together with third party logging enabled.
Then scan this file only and send me the debug logging. I think we'll get more info from that.

**Comment by Zeusy123** [comment]
gonna quite for then ight, will do tomorrow for you :)
