### ISSUE TITLE
Improvement: ability to set time of scan

### ISSUE THREAD

**Issue by Zeusy123** [h3llrais3r/Auto-Subliminal#20]
In General perhaps has an ability of changing how often you want a disk scan?
Current 1hour, I've large libary and i would perfer to scan maybe once or twice a day only.

**Comment by h3llrais3r** [comment]
This is already available.
You can set interval for disk scanning and subtitle checking.

![image](https://user-images.githubusercontent.com/1945295/34083410-b7c20106-e370-11e7-8a1c-d589b96bcdf3.png)
