### ISSUE TITLE
Error related to git in latest version

### ISSUE THREAD

**Issue by popjunkie79** [h3llrais3r/Auto-Subliminal#21]
Hi h3llrais3r,
I'd like to thank you for all your work and for still updating this project. I'm a complete noob when it comes to python so I don't quite understand this error that I get with the latest version of Auto-subliminal. Apparently, something called "git" is now required? Could you help me out with that?

**Traceback (most recent call last):
  File "AutoSubliminal.py", line 134, in <module>
    sys.exit(main())
  File "AutoSubliminal.py", line 100, in main
    import autosubliminal.application
  File "D:\Users\nico5\Documents\Auto-Subliminal-master\autosubliminal\application.py", line 16, in <module>
    from autosubliminal.versionchecker import VersionChecker
  File "D:\Users\nico5\Documents\Auto-Subliminal-master\autosubliminal\versionchecker.py", line 8, in <module>
    from git import Repo
  File "D:\Users\nico5\Documents\Auto-Subliminal-master\lib\git\__init__.py", line 82, in <module>
    refresh()
  File "D:\Users\nico5\Documents\Auto-Subliminal-master\lib\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "D:\Users\nico5\Documents\Auto-Subliminal-master\lib\git\cmd.py", line 293, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet**

**Comment by h3llrais3r** [comment]
How did you install Aut-Subliminal?
Do you have git installed on your local machine?
Can you send me your debug log?

**Comment by popjunkie79** [comment]
Ooooh sorry I thought git stood for github. I just installed git and it seems to work!

**Comment by h3llrais3r** [comment]
No problem, thanks for logging this.
The application should not crash when git is not installed on your machine.
Going to fix this asap!

**Comment by h3llrais3r** [comment]
Merged and released. 
If you have the time, can you retry the startup of latest master version without git installed?

**Comment by popjunkie79** [comment]
Yep it's fixed thank you! So I don't need git anymore, correct?

**Comment by h3llrais3r** [comment]
Indeed, should work without git now.
Thanks for the feedback.
