### ISSUE TITLE
Legendas.tv provider credentials

### ISSUE THREAD

**Issue by theman480** [h3llrais3r/Auto-Subliminal#213]
First I have to thank you for the amazing provider and second there's no Field to user and pass on Legendastv, to download subtitles there we need to login first, can you help me?

**Comment by h3llrais3r** [comment]
Can you try latest development branch?
Should have been fixed with commit cd0aab1c.

**Comment by theman480** [comment]
> @theman480 Can you try latest development branch?
> Should have been fixed with commit [cd0aab1](https://github.com/h3llrais3r/Auto-Subliminal/commit/cd0aab1c0f7518b61931053ab9753ea8cad947f8).

Same problem with lastest development branch:

[](https://i.imgur.com/An2wjWP.png)

**Comment by theman480** [comment]
> @theman480 Can you try latest development branch?
> Should have been fixed with commit [cd0aab1](https://github.com/h3llrais3r/Auto-Subliminal/commit/cd0aab1c0f7518b61931053ab9753ea8cad947f8).

Works perfectly!

I have only one more problem, there's 340 movies on my dedicated server.
I successful configure the disk on "General" tab the problem is after the disk scan, it's loading on "Home" show the 340 movies number but then I get a blank page like this:
https://i.imgur.com/NezMIKw.png

**Comment by h3llrais3r** [comment]
Can you post the log file and perhaps a screenshot of chrome devtools (F12 when running chrome to see if there are issues?

**Comment by theman480** [comment]
> @theman480 Can you post a screenshot of chrome devtools (F12 when running chrome) to see if there are issues?

Here is the error on chrome console after the page loads:

`vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
t.permission @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt1135525', 'The Slammin' Salmon (2009)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt1135525', 'The Slammin' Salmon (2009)')"


2087|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
2088|                                                      </a>
2089|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt1135525', 'The Slammin' Salmon (2009)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2090|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
2091|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt1924435', 'Let's Be Cops (2014)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt1924435', 'Let's Be Cops (2014)')"


3797|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
3798|                                                      </a>
3799|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt1924435', 'Let's Be Cops (2014)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3800|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
3801|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt4160708', 'Don't Breathe (2016)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt4160708', 'Don't Breathe (2016)')"


7408|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
7409|                                                      </a>
7410|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt4160708', 'Don't Breathe (2016)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7411|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
7412|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt4935372', 'The Devil's Candy (2015)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt4935372', 'The Devil's Candy (2015)')"


9208|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
9209|                                                      </a>
9210|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt4935372', 'The Devil's Candy (2015)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9211|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
9212|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt0395584', 'The Devil's Rejects (2005)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt0395584', 'The Devil's Rejects (2005)')"


9748|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
9749|                                                      </a>
9750|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0395584', 'The Devil's Rejects (2005)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9751|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
9752|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

avoid using JavaScript keyword as property name: "with"
  Raw expression: @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess with the Zohan (2008)')"

10745|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
10746|                                                      </a>
10747|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess with the Zohan (2008)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10748|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
10749|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess With The Zohan (2008)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess With The Zohan (2008)')"


10835|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
10836|                                                      </a>
10837|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess With The Zohan (2008)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10838|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
10839|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt1232200', 'That's My Boy (2012)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt1232200', 'That's My Boy (2012)')"


10925|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
10926|                                                      </a>
10927|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt1232200', 'That's My Boy (2012)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10928|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
10929|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

avoid using JavaScript keyword as property name: "with"
  Raw expression: @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess with the Zohan (2008)')"

14263|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
14264|                                                      </a>
14265|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess with the Zohan (2008)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14266|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
14267|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt1723121', 'We're the Millers (2013)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt1723121', 'We're the Millers (2013)')"


14713|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
14714|                                                      </a>
14715|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt1723121', 'We're the Millers (2013)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14716|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
14717|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt0454945', 'She's the Man (2006)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt0454945', 'She's the Man (2006)')"


17053|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
17054|                                                      </a>
17055|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0454945', 'She's the Man (2006)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17056|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
17057|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt0108052', 'Schindler's List (1993)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt0108052', 'Schindler's List (1993)')"


17323|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
17324|                                                      </a>
17325|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0108052', 'Schindler's List (1993)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17326|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
17327|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt0067341', 'Let's Scare Jessica to Death (1971)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt0067341', 'Let's Scare Jessica to Death (1971)')"


20473|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
20474|                                                      </a>
20475|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0067341', 'Let's Scare Jessica to Death (1971)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20476|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
20477|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

    openSettingsModal($event, 'movie', 'tt0256009', 'The Devil's Backbone (2001)')

  Raw expression: @click="openSettingsModal($event, 'movie', 'tt0256009', 'The Devil's Backbone (2001)')"


23443|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
23444|                                                      </a>
23445|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0256009', 'The Devil's Backbone (2001)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23446|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
23447|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

avoid using JavaScript keyword as property name: "with"
  Raw expression: @click="openSettingsModal($event, 'movie', 'tt0068370', 'Children Shouldn't Play with Dead Things (1972)')"

24523|                                                          <i class="fa fa-imdb" aria-hidden="true" title="Click to visit Imdb"></i>
24524|                                                      </a>
24525|                                                      <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0068370', 'Children Shouldn't Play with Dead Things (1972)')">
   |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
24526|                                                          <i class="fa fa-wrench" aria-hidden="true" title="Click to edit movie settings"></i>
24527|                                                      </a>

(found in <Root>)
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1`

**Comment by h3llrais3r** [comment]
Ok, I think I see the problem... You get errors for titles with a `'` in the name....
Will have a look.

**Comment by theman480** [comment]
> Ok, I think I see the problem... You get errors for titles with a `'` in the name....
> Will have a look.

Thank you for the amazing tool/support!

**Comment by theman480** [comment]
Everything Works perfectly, the only problem is on the Homepage in "Lang" always we have the England Flag, Does not matter which language we set.

**Comment by theman480** [comment]
There's one more bug, OpenSubtitles is downloading subtitles only in English, my language on "General" is Brazilian Portuguese, Legendastv downloads amazingly fast the Pt-BR subtitles.
