### ISSUE TITLE
Blank home page when having titles with quotes

### ISSUE THREAD

**Issue by h3llrais3r** [h3llrais3r/Auto-Subliminal#215]
I have only one more problem, there's 340 movies on my dedicated server.
I successful configure the disk on "General" tab, the problem is after the disk scan, it's loading on "Home" and shows the 340 movies numbers but then I get a blank page like this:

https://i.imgur.com/NezMIKw.png

_Originally posted by @theman480 in https://github.com/h3llrais3r/Auto-Subliminal/issues/213#issuecomment-531982732_

**Comment by h3llrais3r** [comment]
@theman480, please continue second bug in this issue.

**Comment by h3llrais3r** [comment]
Here is the error on chrome console after the page loads:

vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
t.permission @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt1135525', 'The Slammin' Salmon (2009)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt1135525', 'The Slammin' Salmon (2009)')"

2087|
2088|
2089| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt1135525', 'The Slammin' Salmon (2009)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2090|
2091|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt1924435', 'Let's Be Cops (2014)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt1924435', 'Let's Be Cops (2014)')"

3797|
3798|
3799| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt1924435', 'Let's Be Cops (2014)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3800|
3801|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt4160708', 'Don't Breathe (2016)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt4160708', 'Don't Breathe (2016)')"

7408|
7409|
7410| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt4160708', 'Don't Breathe (2016)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7411|
7412|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt4935372', 'The Devil's Candy (2015)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt4935372', 'The Devil's Candy (2015)')"

9208|
9209|
9210| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt4935372', 'The Devil's Candy (2015)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9211|
9212|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt0395584', 'The Devil's Rejects (2005)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt0395584', 'The Devil's Rejects (2005)')"

9748|
9749|
9750| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0395584', 'The Devil's Rejects (2005)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9751|
9752|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

avoid using JavaScript keyword as property name: "with"
Raw expression: @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess with the Zohan (2008)')"

10745|
10746|
10747| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess with the Zohan (2008)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10748|
10749|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess With The Zohan (2008)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess With The Zohan (2008)')"

10835|
10836|
10837| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess With The Zohan (2008)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10838|
10839|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt1232200', 'That's My Boy (2012)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt1232200', 'That's My Boy (2012)')"

10925|
10926|
10927| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt1232200', 'That's My Boy (2012)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10928|
10929|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

avoid using JavaScript keyword as property name: "with"
Raw expression: @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess with the Zohan (2008)')"

14263|
14264|
14265| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0960144', 'You Don't Mess with the Zohan (2008)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14266|
14267|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt1723121', 'We're the Millers (2013)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt1723121', 'We're the Millers (2013)')"

14713|
14714|
14715| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt1723121', 'We're the Millers (2013)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14716|
14717|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt0454945', 'She's the Man (2006)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt0454945', 'She's the Man (2006)')"

17053|
17054|
17055| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0454945', 'She's the Man (2006)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17056|
17057|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt0108052', 'Schindler's List (1993)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt0108052', 'Schindler's List (1993)')"

17323|
17324|
17325| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0108052', 'Schindler's List (1993)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17326|
17327|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt0067341', 'Let's Scare Jessica to Death (1971)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt0067341', 'Let's Scare Jessica to Death (1971)')"

20473|
20474|
20475| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0067341', 'Let's Scare Jessica to Death (1971)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20476|
20477|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

invalid expression: missing ) after argument list in

openSettingsModal($event, 'movie', 'tt0256009', 'The Devil's Backbone (2001)')
Raw expression: @click="openSettingsModal($event, 'movie', 'tt0256009', 'The Devil's Backbone (2001)')"

23443|
23444|
23445| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0256009', 'The Devil's Backbone (2001)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23446|
23447|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1
vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1 [Vue warn]: Error compiling template:

avoid using JavaScript keyword as property name: "with"
Raw expression: @click="openSettingsModal($event, 'movie', 'tt0068370', 'Children Shouldn't Play with Dead Things (1972)')"

24523|
24524|
24525| <a class="icon-link" @click="openSettingsModal($event, 'movie', 'tt0068370', 'Children Shouldn't Play with Dead Things (1972)')">
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
24526|
24527|

(found in )
ce @ vendor.min.js?v=3b626554-068b-4155-a7d7-d741fa485998:1

**Comment by h3llrais3r** [comment]
@theman480 Should have been fixed in development branch with commit 84573d4a9fe6379fb2262dc582ea8bf913fcd50f
Can you try?

**Comment by theman480** [comment]
> @theman480 Should have been fixed in development branch with commit [84573d4](https://github.com/h3llrais3r/Auto-Subliminal/commit/84573d4a9fe6379fb2262dc582ea8bf913fcd50f)
> Can you try?

Everything working perfectly.
I think there's only one bug, on the Home the "Lang" shows an England flag and my language is set to Brazilian Portuguese:

https://i.imgur.com/qZSrexL.png

**Comment by h3llrais3r** [comment]
I don't think this is a bug. I assume you did an initial scan with 'English' as wanted subtitles.
Ydouble check that your default language is set to `pt_br`, clean your wanted items and do a new disk scan. (Can be done from System menu).

Just a remark: you won't be able to find good subtitles, as you have already renamed your movies... The tool can only fetch good/in sync subtitles when you let it search on it's original release name... 
In your case, all necessary fiels (source, quality, ...) are not available.

**Comment by theman480** [comment]
> I don't think this is a bug. I assume you did an initial scan with 'English' as wanted subtitles.
> Double check that your default language is set to `pt-BR`, clean your wanted items and do a new disk scan. (Can be done from System menu).
> 
> Just a remark: you won't be able to find good/in sync subtitles, as you have already renamed your movies... The tool can only fetch good/in sync subtitles when you let it search on it's original release name...
> In your case, all necessary fields (source, quality, ...) are not available. So it might find subtitles, but the risk of out of sync subtitles will be big...

So the right way to use your amazing tool is disable couchpotato renamer? Then check subtitltes and manually rename the movies on couchpotato?

**Comment by theman480** [comment]
In couchpotato settings I set it to File Naming <original>" I think now the problem is solved.

**Comment by h3llrais3r** [comment]
Yes, keep the original name 
Or download in separate folder and configure auto-subliminal to scan that folder. 
Create a postprocessing script that moves the files together with the found subtitles to the import folder of couchpotato. Couchpotato will now rename both your files and your subitle with your naming pattern.

**Comment by h3llrais3r** [comment]
Will close this now. In case you should have another issue, please open a new one.
