### ISSUE TITLE
Using insecure websockets when sitting behind nginx reverse proxy

### ISSUE THREAD

**Issue by kbirger** [h3llrais3r/Auto-Subliminal#217]
### INFO

**OS:** Linux Mint
**Version:** 19
**Git branch:** master
**Git version:** 3.0
**Python version:** 3.6.7

**What did you do:** configured a proxy_redirect from my https host to http://localhost:xxx
**What did you expect:** the site to work when accessed from https://externaldomain.com/autosubliminal
**What happened:** error in browser consoleabout using insecure websockets when the page was loaded via ssl.

It seems that autosubliminal is not detecting that the page was loaded over HTTPS. Two possible causes: 1. you don't ever expect the page to be loaded via TLS; 2. You are checking whether the root request comes via http, which is does because TLS terminates at nginx. 

Possible solutions: a config point which specifies that everything should use HTTPS/WSS, or looking at window.location.origin to detect https

**Comment by h3llrais3r** [comment]
I don't have the possibility to test this, so it's not easy to fix this.
If you know a bit of coding, it would be nice that you try to fix it and create a PR.

**Comment by h3llrais3r** [comment]
Ok, after some investigation, I might have found a solution for the insecure websocket.
@kbirger Can you try with the latest development branch, commit 8da33592 might be the fix.

**Comment by kbirger** [comment]
Do you have wss implemented/enabled in your websockets library? I now get a 500:

Error during WebSocket handshake: Unexpected response code: 500

**Comment by h3llrais3r** [comment]
I only changed the protocol to `wss` when `https` is used.
Like I said, I can't test because I don't have `https` setup...

**Comment by h3llrais3r** [comment]
Is your nginx setup ok?
You might find some information at https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup

**Comment by kbirger** [comment]
You're right. I had not thought about it, but additional stuff would have to be added to get it to do the upgrade. For anyone who is reading this later, the following section was necessary:
```nginx
        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
```

My entire config, which works, is:
```nginx
    location /autosubliminal {
      proxy_pass http://autosubliminal;
      auth_basic off; # this is handled by autosubliminal internally

      # Websocket
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 86400;
    }
```

and also, you have to define an upstream to get that to work :).

Thanks for the fix!

**Comment by h3llrais3r** [comment]
@kbirger Thanks for the feedback, will add it to the wiki for the future 😉
