### ISSUE TITLE
Auto-sub not opening webpage

### ISSUE THREAD

**Issue by TEREREZZ** [h3llrais3r/Auto-Subliminal#240]
### INFO

**OS:** Windows 10
**Version:** 1903
**Git branch:**
**Git version:**
**Python version:** 2.7.17

**What did you do:** I upgraded Python and then downgraded it again, also rebooted between. So currently have version 2.7.17. I used to have auto subliminally and it worked, only after updating Python to a 3.0 version it doesn't work anymore.
**What did you expect:** Auto subliminally to boot like normal. 
**What happened:** Nothing happens, very short command prompt opens and then closes, nothing starts.

### ERROR
```
PASTE LOGS HERE (ENABLE DEBUG LOGGING BEFORE REPRODUCING)
```

**Comment by h3llrais3r** [comment]
Try starting it from the command line and paste the output here.

**Comment by TEREREZZ** [comment]
> Try starting it from the command line and paste the output here.
> You also might need to delete the cache folder in your autosubliminal folder before restarting.

Thank you for your reply. Here's the output;

C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019>autosubliminal.py
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\AutoSubliminal.py", line 155, in <module>
    sys.exit(main())
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\AutoSubliminal.py", line 63, in main
    import autosubliminal
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\autosubliminal\__init__.py", line 5, in <module>
    import pkg_resources
ImportError: No module named pkg_resources

C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019>

**Comment by h3llrais3r** [comment]
I think there might be something wrong with your install...
Normally an installation of Python comes with setuptools, which seems to be missing in your case.
Can you do a `pip list` to see what's installed in your python installation?

**Comment by TEREREZZ** [comment]
Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip list
  File "<stdin>", line 1
    pip list
           ^
SyntaxError: invalid syntax
>>>

**Comment by TEREREZZ** [comment]
> I think there might be something wrong with your install...
> Normally an installation of Python comes with setuptools, which seems to be missing in your case.
> Can you do a `pip list` to see what's installed in your python installation?

Hi sir,

Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip list
  File "<stdin>", line 1
    pip list
           ^
SyntaxError: invalid syntax
>>>






Was the result. Could be I unchecked something in the setup, could be. Not sure

**Comment by h3llrais3r** [comment]
Did you do a new installation? It seems that your python installation is not added tot your path environment variables.
I suggest you delete your current python installation.
Do a clean installation, and make sure that python is added to the environment variables.

**Comment by TEREREZZ** [comment]
> Did you do a new installation? It seems that your python installation is not added tot your path environment variables.
> I suggest you delete your current python installation.
> Do a clean installation, and make sure that python is added to the environment variables.

Ty sir.

It didn't work. WHen  I know try to start 'python' when running a random CMD it will work, python starts. WHen I try to run AutoSubliminal.py via CMD same error. 


It used to work , I've completely removed auto subliminally that used to work so I guess this is a clean version of auto sublinally ? How can I be sure of that, maybe something in localappdata?

**Comment by h3llrais3r** [comment]
If `pip` is not recognized, python is not added to the path...
Please rerun your installer and make sure you check `Add python to path` checkbox.
If this is done, restart pc, open command prompt (cmd.exe) and type `python --version`. and post output here.

**Comment by TEREREZZ** [comment]
> If `pip` is not recognized, python is not added to the path...
> ![image](https://user-images.githubusercontent.com/1945295/67419844-bb3dc880-f5cd-11e9-993d-bd280bada2d1.png)
> 
> Please rerun your installer and make sure you check `Add python to path` checkbox.
> If this is done, restart pc, open command prompt (cmd.exe) and type `python --version`. and post output here.

Wait I've been installing Python 2.7.17 the whole time, I can install 3.x ? 

So far pip is not recognized, when I follow your instructions for python --version I get the correct output;

C:\Users\x>python --version
Python 2.7.17

**Comment by h3llrais3r** [comment]
No problem, should work with python 2.7.17 as well. I'm running it on 2.7.15...

**Comment by h3llrais3r** [comment]
Ok, let's check the following:
your `path` environment variable should contain your python paths. You can check it by typing `path` in a command window. It should contain your path to python installation dir, and the installation dir scripts folder (see below)
```
C:\Users\ADMIN>path
PATH=C:\Tools\Python27;C:\Tools\Python27\Scripts;
```
Please also post screenshot of content of your scripts folder... it should contain pip.exe.

**Comment by TEREREZZ** [comment]
> Ok, let's check the following:
> your `path` environment variable should contain your python paths. You can check it by typing `path` in a command window. It should contain your path to python installation dir, and the installation dir scripts folder (see below)
> 
> ```
> C:\Users\ADMIN>path
> PATH=C:\Tools\Python27;C:\Tools\Python27\Scripts;
> ```
> 
> Please also post screenshot of content of your scripts folder... it should contain pip.exe.

C:\Users\x>path
PATH=C:\Program Files\Python27\;C:\Program Files\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Calibre2\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\FileBot\;C:\Users\x\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Python2.7;





no scripts folder in my installation folder
https://i.imgur.com/28srMr8.png

**Comment by h3llrais3r** [comment]
I see 2 different installations in your path...

- C:\Program Files\Python27
- C:\Program Files\Python2.7

Please remove the last one from your path.
I still think you need to rerun your python installer and check the options...
Use 64bit installer and install for all users:
![image](https://user-images.githubusercontent.com/1945295/67421146-31432f00-f5d0-11e9-8f19-9f8b5fb154f9.png)
Make sure all options are installed from disk:
![image](https://user-images.githubusercontent.com/1945295/67421216-59329280-f5d0-11e9-86ec-193485dd19f4.png)

**Comment by TEREREZZ** [comment]
Aiaiaiai it just won't work. Python in CMD works but pip doesn't.

I've removed the Python installatio nagain, checked the environment variables & reinstalled it, this is it how it shows;

https://i.imgur.com/9aJbsaX.png

Pip doesn't do anything useful when typied in CMD

**Comment by h3llrais3r** [comment]
You really have strange paths... python27777777?
Try installing it in c:\python27 as proposed by default and not in c:\program files...
It seems to add it correctly to your path, but no scripts folder?
Really strange...

**Comment by h3llrais3r** [comment]
I think you should still be able to run your old setup as you have a backup.
Just start `Autosubliminal.py` from your backup folder and it should work.
