### ISSUE TITLE
missing languages flags attached

### ISSUE THREAD

**Issue by Zeusy123** [h3llrais3r/Auto-Subliminal#25]
Heres some flag images which is missing from you source:
file attached:

**Comment by Zeusy123** [comment]
i dont think  file attached last time i posted this trying individual files.
![da](https://user-images.githubusercontent.com/24862324/35634469-107b00a0-06ac-11e8-85fb-11a7f49463d9.png)
![el](https://user-images.githubusercontent.com/24862324/35634471-10a9d128-06ac-11e8-9267-8e5884ae7c9c.png)
![he](https://user-images.githubusercontent.com/24862324/35634472-10cd90e0-06ac-11e8-9137-e8275bbe5ec5.png)
![hi](https://user-images.githubusercontent.com/24862324/35634473-110560ec-06ac-11e8-9d8f-791b867f0ce3.png)
![ja](https://user-images.githubusercontent.com/24862324/35634474-115112bc-06ac-11e8-8207-36e3da6b3d1d.png)
![ko](https://user-images.githubusercontent.com/24862324/35634475-1177e518-06ac-11e8-9c97-c8984b09339c.png)
![uk](https://user-images.githubusercontent.com/24862324/35634477-119dbe46-06ac-11e8-95d9-730296ae751d.png)
![zh](https://user-images.githubusercontent.com/24862324/35634479-124e8b36-06ac-11e8-9116-d34d8ce4c972.png)

**Comment by h3llrais3r** [comment]
Please also provide language code for the flags...

**Comment by Zeusy123** [comment]
added:)

**Comment by h3llrais3r** [comment]
I just had a quick look, and the flags are already there... but they are listed under the country code instead of the language code...
This probably means that we need a complete rename of all flags to match the language code instead of the country code.
F.e.: Japanese is available under **jp** (japan) while the language code should be **ja** (japanese).

**Comment by Zeusy123** [comment]
those where the only ones i found to be missing/named wrongly. :)

**Comment by h3llrais3r** [comment]
Fixed with commit 4a9783faddae584d9283918091f462d2637a281f

**Comment by Zeusy123** [comment]
great job:)
now if i can figure out why AS keeps crashing out after 10-15mins

**Comment by h3llrais3r** [comment]
Please keep discussion for that in other issue.
This one can be closed once I merge it into master.
