### ISSUE TITLE
Can this be run on a synology nas

### ISSUE THREAD

**Issue by abescalamis** [h3llrais3r/Auto-Subliminal#29]
### INFO

**OS:**
**Version:**
**Git branch:**
**Git version:**
**Python version:**

**What did you do:**
**What did you expect:**
**What happened:**
I didn't know where to ask but can this be run from a synology NAS?

### ERROR
```
PASTE LOGS HERE (ENABLE DEBUG LOGGING BEFORE REPRODUCING)
```

**Comment by h3llrais3r** [comment]
I suppose yes. I would say, just give it a try. 😉
