### ISSUE TITLE
UserWarning: You don't have the C version of NameMapper installed!

### ISSUE THREAD

**Issue by schumi2004** [h3llrais3r/Auto-Subliminal#31]
### INFO

**OS:**Synology DSM6 
**Version:**
**Git branch:**master
**Git version:**
**Python version:**2.7.13

**What did you do:**Followed instructions runnig it on a virtual python environment
**What did you expect:**
**What happened:**When namemapper is configured it returns an error that it needs the C version of NameMapper

### ERROR
```
/volume1/@appstore/virtualenv/autosubliminal/lib/Cheetah/Compiler.py:1509: UserWarning:
You don't have the C version of NameMapper installed! I'm disabling Cheetah's useStackFrames option as it is painfully slow with the Python version of NameMapper. You should get a copy of Cheetah with the compiled C version of NameMapper.
  "\nYou don't have the C version of NameMapper installed! "
```
Any solution to get rid of this error and have name mapping working?

**Comment by h3llrais3r** [comment]
@schumi2004, this is only a warning, you can safely ignore it.
I have the same warning on windows but this doesn't seem to slow anything down.
To get rid of it, we need a custom compiled version of cheetah.

But, I've removed the cheetah dependency in the `development` branch, so no worries, it will no longer be a warning in the next release. :wink:
