### ISSUE TITLE
[Request] creation of PID file so it can be monitored with Monit.

### ISSUE THREAD

**Issue by schumi2004** [h3llrais3r/Auto-Subliminal#38]
Would it be possible to let AutoSubliminal create a PID file so it can be monitored with Monit?
I checked my system but couldn't find one.

**Comment by h3llrais3r** [comment]
@schumi2004 I checked some other projects (like Medusa and Sickrage) and they are creating pid files through the init scripts. I suggest you do the same.
An example: https://github.com/h3llrais3r/Auto-Subliminal/blob/development/init.ubuntu
Other examples can be found (for other os) at https://github.com/pymedusa/Medusa/tree/master/runscripts
