### ISSUE TITLE
opensubtitles SSL error

### ISSUE THREAD

**Issue by WinDanesz** [h3llrais3r/Auto-Subliminal#56]
### INFO

Tried to download subs, but got an opensubtitles SSL error in logs. 

**OS:** 
Windows 10
**Version:** 
1607
**Git branch**: 
master
**Git version:**
2.6
**Python version:**
 3.7

**What did you do:**
 search for subtitles by pressing System > Check subtitles
**What did you expect:**
 find some subtitles (mostly from opensubtitles)
**What happened:**
 couldn't find subtitles, but the subtitles does exist on opensubtitles (could download with vlsub).

Could be related to this?
https://github.com/slackapi/python-slackclient/issues/334

### ERROR
```
  File "C:\Users\username\AppData\Local\Programs\Python\Python37-32\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)
127.0.0.1 - - [30/Oct/2018:19:52:37] "GET /home/searchSubtitle/2/hu HTTP/1.1" 200 638 "http://localhost:8083/home/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
127.0.0.1 - - [30/Oct/2018:19:52:37] "GET /js/home-manualsearch.js?v=c8485e31-5eb5-4174-bcc0-5faa0ba0aade HTTP/1.1" 200 3313 "http://localhost:8083/home/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
127.0.0.1 - - [30/Oct/2018:20:09:02] "GET /log/viewLog HTTP/1.1" 200 700600 "http://localhost:8083/home/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
127.0.0.1 - - [30/Oct/2018:20:09:04] "GET /system/websocket HTTP/1.1" 101 - "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
```

**Comment by WinDanesz** [comment]
Hi, thanks for the super quick reply. 
Sure, I tried with python 2.7
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32

Wasn't sure where to find this mako folder, so I tried with a fresh install of autosub., got the following error again.

2018-10-30 21:01:15,828 ERROR Provider 'opensubtitles' SSL error 1
Traceback (most recent call last):
  File "C:\Scripts\folder\Auto-Subliminal-2.6.0\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Scripts\folder\Auto-Subliminal-2.6.0\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Scripts\folder\Auto-Subliminal-2.6.0\lib\subliminal\providers\opensubtitles.py", line 143, in initialize
    'subliminal v%s' % __short_version__))
  File "C:\Python27\lib\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "C:\Python27\lib\xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\lib\xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "C:\Python27\lib\xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 369, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 617, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
127.0.0.1 - - [30/Oct/2018:21:01:30] "GET /home/ HTTP/1.1" 200 24284 "http://localhost:8083/home/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
127.0.0.1 - - [30/Oct/2018:21:01:31] "GET /system/websocket HTTP/1.1" 101 - "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
127.0.0.1 - - [30/Oct/2018:21:01:38] "GET /log/viewLog HTTP/1.1" 200 15522 "http://localhost:8083/home/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
127.0.0.1 - - [30/Oct/2018:21:01:39] "GET /system/websocket HTTP/1.1" 101 - "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

**Comment by WinDanesz** [comment]
Probably found the cause... sorry for bothering you :)

Back then I tweaked my hosts file by adding the following line in order to speed up vlsub:
92.240.234.122  api.opensubtitles.org

Thanks for this amazing app! Found it recently so I'm quite new with it.

**Comment by h3llrais3r** [comment]
Mako folder is subfolder located underneath the cache folder in the root dir of the app.
Glad that you sorted it out yourself, because I could not reproduce the error. :wink:
