### ISSUE TITLE
Search deadline should be configurable

### ISSUE THREAD

**Issue by kbirger** [h3llrais3r/Auto-Subliminal#80]
This is a feature request and not a bug, so I've removed the template.

It would be really great if you could configure the deadline parameters in [item.py](https://github.com/h3llrais3r/Auto-Subliminal/blob/master/autosubliminal/core/item.py).

```python
# A subtitle will be searched on each run, as long as the file is not older than 4 weeks
search_deadline = datetime.timedelta(weeks=4)

# Once a video file is older than the search deadline, it will only be searched once a week
search_delta = datetime.timedelta(weeks=1)
```

**Comment by h3llrais3r** [comment]
Available in master.
![image](https://user-images.githubusercontent.com/1945295/54945583-7f0e9080-4f36-11e9-81aa-0e5a350b82ca.png)
