### ISSUE TITLE
Is project Alive ?

### ISSUE THREAD

**Issue by DisasteR** [h3llrais3r/Auto-Subliminal#9]
Hi, is your project still alive ?

**Comment by h3llrais3r** [comment]
Yes it is. Please check the development branch if you want to try the latest version.

**Comment by DisasteR** [comment]
Yeah just saw that your dev branch is active.
Can you explain the difference beetween your work and https://github.com/BenjV/autosub-bootstrapbill ?

Didn't try both and wanted to know features and differences before go.

**Comment by h3llrais3r** [comment]
I never tried autosub-bootstrapbill... but they are both based on the same old autosub.
It should do basicly the same... but each with his own features...
